[project]
name = "tg-bot-message-storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.19.0",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
]
